; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; === Firmware chinh (Pick & Place) ===
[env:esp32s3usbotg]
platform = espressif32
board = esp32s3usbotg
framework = arduino
lib_deps =
    madhephaestus/ESP32Servo@^3.0.0
    adafruit/Adafruit_VL53L0X@^1.2.0
    adafruit/Adafruit SSD1306@^2.5.7
build_src_filter = +<*> -<test_periph.cpp> -<test_vl53.cpp> -<test_l298n.cpp>
